### ISSUE TITLE
Downloadable resources need rebuilding

### ISSUE THREAD

**Issue by rik-cross** [CodeClub/lesson_format#194] opened 2016-09-02 11:14 UTC
The downloadable project resources are out of date:

![screen shot 2016-09-02 at 12 12 04](https://cloud.githubusercontent.com/assets/18461167/18202232/b1b428c6-7106-11e6-8a6b-262cab31fd6b.png)

Is there a way to rebuild the website and force the .zip files to be regenerated? I'm sure this has been done in the past, but I forget how.

There are probably a few inconsistencies, so if all project resources could be rebuilt, that'd be great.

**Comment by martinpeck** [comment] 2016-09-05 20:57
How can I show that they're out of date?
What should I be looking for?

**Comment by rik-cross** [comment] 2016-09-05 21:01
For example, the files in the "Create Your Own World" should...
https://github.com/CodeClub/scratch-curriculum/tree/master/en-GB/Term%202/Create%20Your%20Own%20World/Project%20Resources

...are different to those in the .zip...
http://projects.codeclubworld.org/en-GB/02_scratch_02/06/scratch_02_2-06_Create_Your_Own_World_resources.zip

**Comment by rik-cross** [comment] 2016-09-05 21:02
This is also true of the files in "Catch the Dots" and "Paint Box".
I think they may be the only ones that need updating.

**Comment by rik-cross** [comment] 2016-09-06 07:51
...oh, and the HTML & CSS projects.

**Comment by martinpeck** [comment] 2016-09-06 15:59
I know what the issue is...it's that the code explicity goes out of its way to NEVER create a zip file if one already exists...

https://github.com/CodeClub/lesson_format/blob/master/build.py#L1305

I'm going to suggest a work around, but want to test it first. The work around is going to be "delete the zip files from the website you want to be regenerated". 

I could add some flag in the code that allows zip files to be generated regardless of their current state, or find some other way to force a regen, but if the "delete the file" approach works it'll do for now.

**Comment by rik-cross** [comment] 2016-09-07 10:16
Hi Martin, deleting the .zips sounds good to me. Even if this adds to the build time, it's almost always done overnight anyway.

**Comment by martinpeck** [comment] 2016-09-07 10:34
I'm not sure my initial suggestion is an option.

**Comment by andylolz** [comment] 2016-09-07 16:21
Looks like this lovely feature was added in cad6f810.

I think the idea was to run autobuild.py with `--clean` to bin everything and rebuild.

**Comment by martinpeck** [comment] 2016-09-07 16:28
Yeah, but neither `--clean` or `--rebuild` appear to help. 
Every nightly build is run with `--clean`.

**Comment by andylolz** [comment] 2016-09-07 16:41
Yeah, I guess that’s due to the [`git checkout -- filename`](https://github.com/CodeClub/lesson_format/blob/6d622029/build.py#L1303).

I guess taking that out and using `--clean` will fix it.

**Comment by martinpeck** [comment] 2016-09-07 16:51
Yeah, so it's related to the "dirty hack" that was added in https://github.com/CodeClub/lesson_format/commit/b682de2dafe5a45c5772017cd19c977150749387 as part of "stop generating PDFs"

It looks like the PDF generation hack is circumvented by `--rebuild` where zipfile generation is not, so I'm considering adding check for `rebuild` around that zipfile hack such that a rebuild does not pull the file from git at all.

**Comment by martinpeck** [comment] 2016-09-09 14:03
@rik-cross can you please confirm that this is now fixed? I'll close this on the assumption that it is, but feel free to open if the zipfiles don't appear to have been rebuilt (from my point of view, and looking at the last PR into the gh-pages repo, the zip files all look nice and fresh).

The change I've made in https://github.com/CodeClub/lesson_format/commit/ce8965f1499a3fc72a6938f033510e91bf651fda means that you can now cause zipfiles to be regenerated by using **both** the `--clean` and `--rebuild` flags of autobuild.py

`--clean` makes sure that the output folder is deleted prior to building things. Otherwise, the existing zip file is used.

`--rebuild` makes sure that the PDFs and zipfiles are rebuilt. Otherwise, it'll use the ones that already exist.

Only by specifying both of these flags will you get zip files to generate.

The nightly build uses just `--clean`, and not the `--rebuild` flag. This could certainly be altered easily, but it might add quite some time to the build. If you'd rather have the zipfiles always be rebuilt then we can add this flag, but if zipfile regeneration is rare then it's easy enough to invoke the build from the heroku command line with...

`heroku run python autobuild.py --rebuild --clean --verbose`

... where `--verbose` is optional, but will give you plenty of feedback on what's going on.

**Closed by martinpeck** 2016-09-09 14:03 UTC
Labels: important

**Comment by rik-cross** [comment] 2016-09-09 14:36
All looks good to me. Thanks @martinpeck and @andylolz :)
Manually running with `--rebuild` if needed works for me.
